version: '3'

services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment: 
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes: 
      - wordpress_data:/var/www/html
    depends_on:
      - mysql
    restart: always
    networks:
      frontend-network
      backend-network

  wpcli:
    image: wordpress:cli-php8.2
    depends on:
      - wordpress
    enviroment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    network:
      backend-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment: 
      - PMA_ARBITRARY=1
    restart: always

    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      frontend-network
      backend-network

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_certs_data:/var/lib/https-portal
    restart: always
    environment:
      DOMAINS: 'practica14-1.ddns.net -> http://wordpress:80'
    restart: always
    networks:
      frontend-network
    
volumes: 
  mysql_data:
  wordpress_data:
  ssl_certs_data:
networks:
  frontend-network:
  backend-network: